// 네이티브(엔진 구현) 함수 식별자와 그 하위 연산 코드들.
// Value::Native(Native::X) 로 값이 되어 JS 에 노출된다.
use super::*;

// canvas 2D 컨텍스트 메서드
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CanvasMethod {
    GetImageData,
    PutImageData,
    CreateImageData,
    CreateLinearGradient,
    CreateRadialGradient,
    AddColorStop,
    CreatePattern,
    Clip,
    BezierCurveTo,
    QuadraticCurveTo,
    Translate,
    Rotate,
    Scale,
    Transform,
    SetTransform,
    ResetTransform,
    Save,
    Restore,
    MeasureText,
    DrawImage,
    Ellipse,
    RoundRect,
    FillRect,
    ClearRect,
    StrokeRect,
    BeginPath,
    MoveTo,
    LineTo,
    Arc,
    Rect,
    ClosePath,
    Fill,
    Stroke,
    FillText,
    Noop, // save/restore/scale/translate/setTransform 등 (근사로 무시)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Native {
    ConsoleLog,
    ArrayPush,
    GetElementById,
    AddEventListener,
    AddGlobalListener,
    FnCall,
    FnApply,
    FnBind,
    FunctionCtor,
    // eval (§19.2.1). 직접 호출은 현재 스코프에서, 간접 호출은 전역 스코프에서 평가한다.
    Eval,
    // Object/Array 전역 자체 (typeof 가 "function" 이어야 하고 호출/new 가 가능해야 함)
    ObjectCtor,
    ArrayCtor,
    ObjectDefineProperty,
    ObjectCreate,
    ObjectFreeze,
    ObjectSeal,
    ObjectPreventExt,
    ObjectIsFrozen,
    ObjectIsSealed,
    ObjectIsExtensible,
    ObjectGetPrototypeOf,
    ObjectSetPrototypeOf,
    ObjectDefineProperties,
    ObjectGetOwnPropertySymbols,
    ObjectIsPrototypeOf,
    HasOwnProperty,
    ObjToString,
    // Error.prototype.toString (§20.5.3.4): name + ": " + message (빈 쪽은 생략)
    ErrorToString,
    ReturnFalse,
    ReturnThis, // valueOf 등 — 수신자(this) 반환
    FnToString, // Function.prototype.toString
    MakeIter,
    IterNext,
    // 지연 제너레이터 반복자 프로토콜 (generator.rs)
    GenNext,
    GenReturn,
    GenThrow,
    // Symbol 원시값 (Symbol()/Symbol.for/Symbol.keyFor)
    SymbolCtor,
    SymbolFor,
    SymbolKeyFor,
    // getComputedStyle(el) 과 그 반환 뷰의 getPropertyValue(name)
    GetComputedStyle,
    MatchMedia,
    ComputedGetProperty,
    // a.compareDocumentPosition(b) — 문서 순서 비트마스크 (jQuery sortOrder)
    CompareDocPosition,
    // document.implementation.createHTMLDocument(title) — 분리된 문서
    CreateHTMLDocument,
    DocQuery(&'static str),
    CreateTextNode,
    // document.createComment (§4.5.1). 코멘트 노드는 DOM 의 일부다.
    CreateComment,
    // CharacterData 메서드 (§4.9): 텍스트/코멘트의 문자 데이터 조작.
    CharData(CharDataOp),
    // Text.splitText(offset) (§4.10): 텍스트 노드를 둘로 쪼갠다.
    SplitText,
    // Attr 노드 접근 (§4.9.2)
    GetAttributeNode,
    // CSSOM (§CSSOM 6)
    StyleSheets,
    // 플랫폼 객체의 브랜드 문자열 (§WebIDL 의 인터페이스 판별). instanceof 에 쓴다.
    Brand,
    // NodeList/CSSRuleList 의 item(i) — 표준 컬렉션 인터페이스
    ListItem,
    SheetInsertRule,
    SheetDeleteRule,
    RuleStyleGet,
    RuleStyleSet,
    RuleStyleRemove,
    RuleStyleItem,
    SetAttributeNode,
    RemoveAttributeNode,
    // document.defaultView → window
    WindowSelf,
    // Element.setAttributeNS/getAttributeNS/… (§4.9.2). SVG/XML 이 쓴다.
    SetAttributeNS,
    GetAttributeNS,
    RemoveAttributeNS,
    HasAttributeNS,
    InsertBefore,
    StyleSetProperty,
    StyleGetProperty,
    StyleRemoveProperty,
    ClassAdd,
    ClassRemove,
    ClassToggle,
    ClassContains,
    RegExpCtor,
    RegexTest,
    RegexExec,
    StringCtor,
    NumberCtor,
    BooleanCtor,
    StrFromCharCode,
    NumIsInteger,
    NumIsFinite,
    NumIsNaN,
    NumToFixed,
    ValueToStr, // recv.toString([radix]) → 문자열
    ValueOfSelf, // recv.valueOf() → recv
    DateNow,
    DateParse, // Date.parse(str) → millis
    DateUTC,   // Date.UTC(y,m,d,...) → millis
    DateCtor,
    DateMethod(DateField),
    XhrCtor,
    UrlCtor,
    UrlToString,
    UrlSearchGet,
    UrlSearchGetAll,
    UrlSearchHas,
    UrlSearchSet,
    UrlSearchAppend,
    UrlSearchDelete,
    UrlSearchToString,
    XhrOpen,
    XhrSend,
    XhrSetHeader,
    XhrGetHeader,
    EventPreventDefault,
    EventStopProp,
    GetElementsByClass,
    GetElementsByTag,
    MapCtor,
    SetCtor,
    Map(MapOp),
    Set(SetOp),
    ErrorCtor(&'static str),
    CreateElement,
    AppendChild,
    NodeAppend,
    NodePrepend,
    NodeBefore,
    NodeAfter,
    NodeReplaceWith,
    GetBoundingClientRect,
    DispatchEvent,
    RemoveEventListener,
    RemoveGlobalListener,
    DispatchGlobalEvent,
    TakeMutations,
    DynamicImport,
    QueueMicrotask,
    CssSupports,
    ElementAnimate,
    GetAttributeNames,
    HasAttributes,
    ToggleAttribute,
    ReplaceChildren,
    GetAnimations,
    AttachShadow,
    InsertAdjacentHTML,
    InsertAdjacentElement,
    ScrollTo,
    ScrollBy,
    ScrollIntoView,
    Focus,
    Blur,
    ActiveElement,
    LocationHref,
    BigIntCtor,
    BigIntToString,
    DocWrite,
    CookieGet,
    CookieSet,
    GetNamedItem,
    LsKey,
    LsLength,
    HeadersGet,
    HeadersHas,
    ObjectGetOwnPropertyDescriptor,
    LocationAssign,
    LocationReload,
    LocationHrefSet,
    Escape,
    Unescape,
    HistoryPushState,
    HistoryReplaceState,
    DomParserCtor,
    DomParserParse,
    EventCtor,
    CloneNode,
    Matches,
    Closest,
    DomContains,
    CreateDocumentFragment,
    ProxyCtor,
    CanvasGetContext,
    Canvas(CanvasMethod),
    RemoveElement,
    SetAttribute,
    GetAttribute,
    QuerySelector,
    QuerySelectorAll,
    Math(MathOp),
    Str(StrOp),
    Arr(ArrOp),
    JsonParse,
    JsonStringify,
    ParseInt,
    ParseFloat,
    EncodeUri,
    EncodeUriComponent,
    DecodeUri,
    DecodeUriComponent,
    IsNaN,
    LsGetItem,
    LsSetItem,
    LsRemoveItem,
    LsClear,
    Alert,
    // 받고 아무것도 안 함 (window.addEventListener 등 — 창 이벤트는 아직 없음)
    Noop,
    StructuredClone,
    ReflectGet,
    ReflectSet,
    ReflectHas,
    ReflectDeleteProperty,
    ReflectApply,
    ReflectConstruct,
    ObjectKeys,
    ObjectValues,
    ObjectEntries,
    ObjectFromEntries,
    ObjectAssign,
    ArrayIsArray,
    ArrayFrom, // Array.from(iterable|array-like, mapFn?)
    ArrayOf,   // Array.of(...args)
    SetTimeout,
    SetInterval,
    ClearTimer,
    // Promise/fetch
    PromiseCtor,          // new Promise(executor)
    PromiseSettleResolve, // executor 의 resolve (this=promise)
    PromiseSettleReject,  // executor 의 reject (this=promise)
    PromiseResolve,
    PromiseReject,
    PromiseAll,
    PromiseRace,
    PromiseAllSettled,
    PromiseThen,
    PromiseCatch,
    PromiseFinally,
    Identity, // 값 통과 (promise 체이닝용)
    Fetch,
    ResponseText,
    ResponseJson,
    // Response.arrayBuffer() — 원본 바이트 그대로 (텍스트로 거치면 바이너리가 망가진다)
    ResponseArrayBuffer,
    CurrentScript,
    // document.createElementNS(namespace, qualifiedName)
    CreateElementNS,
    // element.click() — 합성 클릭 이벤트를 실제로 디스패치한다 (HTML §8.3.5).
    // 없으면 프로그램적 클릭 한 줄에 스크립트가 죽는다 (탭 전환/다운로드 트리거 등 흔하다).
    ElementClick,
    // WebSocket (RFC 6455) — 진짜 소켓이다. 스텁이면 "연결됐다" 는 거짓말이 된다.
    WebSocketCtor,
    WsSend,
    WsClose,
    // ArrayBuffer 의 0 채우기. JS 루프로 채우면 1MB 버퍼가 100만 번 반복이라
    // 사실상 못 쓴다 (wasm 메모리는 최소 1MB 로 시작하는 게 보통).
    ZeroBytes,
    // WebAssembly. 프렐류드의 얇은 JS 껍데기가 이 네이티브들을 부른다.
    WasmValidate,
    WasmCompile,
    WasmMemPages,
    WasmRegisterMemory,
    WasmGrow,
    WasmInstantiate,
    // 내보내진 wasm 함수 (인스턴스 인덱스, 함수 인덱스)
    WasmCall(u32, u32),
    // 내보내진 전역 (인스턴스, 전역 인덱스) — get/set 접근자
    WasmGlobalGet(u32, u32),
    WasmGlobalSet(u32, u32),
    // 내보내진 테이블 (인스턴스) — table.get(i) / table.length
    WasmTableGet(u32),
    RemoveAttribute,
    HasAttribute,
    RemoveChild,
}

// 예약된 타이머 (창 이벤트 루프 / 헤드리스 flush 가 실행)
pub struct Timer {
    pub id: u64,
    pub callback: Value,
    pub delay_ms: f64,
    pub repeat: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MathOp {
    Floor,
    Ceil,
    Round,
    Abs,
    Min,
    Max,
    Sqrt,
    Pow,
    Random,
    Trunc,
    Sign,
    Cbrt,
    Log,
    Log2,
    Log10,
    Exp,
    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Atan2,
    Hypot,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum StrOp {
    IndexOf,
    LastIndexOf,
    Slice,
    Split,
    Upper,
    Lower,
    Trim,
    Replace,
    ReplaceAll,
    CharAt,
    Includes,
    StartsWith,
    EndsWith,
    Match,
    MatchAll,
    Search,
    PadStart,
    PadEnd,
    Repeat,
    TrimStart,
    TrimEnd,
    CharCodeAt,
    CodePointAt,
    Concat,
    At,
    LocaleCompare,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum DateField {
    Time,
    // setter 계열 (표준 Date 는 가변 객체다 — setter 가 없으면 날짜 계산 코드가 통째로 죽는다)
    SetTime,
    SetFullYear,
    SetMonth,
    SetDate,
    SetHours,
    SetMinutes,
    SetSeconds,
    SetMs,
    FullYear,
    Month,
    Date,
    Day,
    Hours,
    Minutes,
    Seconds,
    Ms,
    TimezoneOffset,
    ToIso,
    ToStr,
    ToDateStr,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MapOp {
    Get,
    Set,
    Has,
    Delete,
    Clear,
    ForEach,
    Keys,
    Values,
    Entries,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SetOp {
    Add,
    Has,
    Delete,
    Clear,
    ForEach,
    Values,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ArrOp {
    Entries,
    Join,
    Pop,
    IndexOf,
    Slice,
    ForEach,
    Map,
    Filter,
    Some,
    Every,
    Reduce,
    Find,
    FindIndex,
    Concat,
    Includes,
    Splice,
    Shift,
    Unshift,
    Reverse,
    Keys,
    Values,
    Sort,
    Flat,
    FlatMap,
    At,
    FindLast,
    FindLastIndex,
    Fill,
    ReduceRight,
}

// CharacterData 의 문자 데이터 연산 (§4.9). 오프셋/길이는 UTF-16 코드 단위 기준.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CharDataOp {
    Substring,
    Append,
    Insert,
    Delete,
    Replace,
}
