// HTML IDL 속성 반영 표 (HTML 표준 §2.6 "Reflecting content attributes in IDL attributes").
// **기계 생성**: WPT 의 html/dom/elements-*.js (표준의 IDL 속성 목록을 그대로 담은
// 데이터)에서 추출했다. 손으로 베끼지 않는다.
//
// missing: 콘텐츠 속성이 없을 때의 값 (missing value default)
// invalid: 알 수 없는 값일 때의 값 (invalid value default)
// 둘 다 없으면 열거형은 빈 문자열이 된다 (표준).
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Reflect {
    String,
    Url,
    Bool,
    Long,
    UnsignedLong,
    Double,
    Enum,
    TokenList,
}

pub struct ReflectSpec {
    pub tag: &'static str, // "" = 모든 HTML 요소 (전역 속성)
    pub idl: &'static str,
    pub attr: &'static str,
    pub kind: Reflect,
    pub keywords: &'static [&'static str],
    pub missing: Option<&'static str>,
    pub invalid: Option<&'static str>,
}

pub static REFLECT: &[ReflectSpec] = &[
    ReflectSpec { tag: "", idl: "accessKey", attr: "accesskey", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "", idl: "autofocus", attr: "autofocus", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "", idl: "className", attr: "class", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "", idl: "dir", attr: "dir", kind: Reflect::Enum, keywords: &["ltr", "rtl", "auto"], missing: None, invalid: None },
    ReflectSpec { tag: "", idl: "hidden", attr: "hidden", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "", idl: "lang", attr: "lang", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "", idl: "tabIndex", attr: "tabindex", kind: Reflect::Long, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "", idl: "title", attr: "title", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "charset", attr: "charset", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "coords", attr: "coords", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "download", attr: "download", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "href", attr: "href", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "hreflang", attr: "hreflang", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "ping", attr: "ping", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "referrerPolicy", attr: "referrerpolicy", kind: Reflect::Enum, keywords: &["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "rel", attr: "rel", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "relList", attr: "rel", kind: Reflect::TokenList, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "rev", attr: "rev", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "shape", attr: "shape", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "target", attr: "target", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "a", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "alt", attr: "alt", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "coords", attr: "coords", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "download", attr: "download", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "href", attr: "href", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "hreflang", attr: "hreflang", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "noHref", attr: "nohref", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "ping", attr: "ping", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "referrerPolicy", attr: "referrerpolicy", kind: Reflect::Enum, keywords: &["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "rel", attr: "rel", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "relList", attr: "rel", kind: Reflect::TokenList, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "shape", attr: "shape", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "target", attr: "target", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "area", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "audio", idl: "autoplay", attr: "autoplay", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "audio", idl: "controls", attr: "controls", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "audio", idl: "crossOrigin", attr: "crossorigin", kind: Reflect::Enum, keywords: &["anonymous", "use-credentials"], missing: None, invalid: Some("anonymous") },
    ReflectSpec { tag: "audio", idl: "defaultMuted", attr: "muted", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "audio", idl: "loading", attr: "loading", kind: Reflect::Enum, keywords: &["lazy", "eager"], missing: Some("eager"), invalid: Some("eager") },
    ReflectSpec { tag: "audio", idl: "loop", attr: "loop", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "audio", idl: "preload", attr: "preload", kind: Reflect::Enum, keywords: &["none", "metadata", "auto"], missing: Some("['none', 'metadata', 'auto']"), invalid: None },
    ReflectSpec { tag: "audio", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "base", idl: "href", attr: "href", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "base", idl: "target", attr: "target", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "blockquote", idl: "cite", attr: "cite", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "body", idl: "aLink", attr: "alink", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "body", idl: "background", attr: "background", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "body", idl: "bgColor", attr: "bgcolor", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "body", idl: "link", attr: "link", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "body", idl: "text", attr: "text", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "body", idl: "vLink", attr: "vlink", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "br", idl: "clear", attr: "clear", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "button", idl: "disabled", attr: "disabled", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "button", idl: "formAction", attr: "formaction", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "button", idl: "formEnctype", attr: "formenctype", kind: Reflect::Enum, keywords: &["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], missing: None, invalid: Some("application/x-www-form-urlencoded") },
    ReflectSpec { tag: "button", idl: "formMethod", attr: "formmethod", kind: Reflect::Enum, keywords: &["get", "post", "dialog"], missing: None, invalid: Some("get") },
    ReflectSpec { tag: "button", idl: "formNoValidate", attr: "formnovalidate", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "button", idl: "formTarget", attr: "formtarget", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "button", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "button", idl: "type", attr: "type", kind: Reflect::Enum, keywords: &["submit", "reset", "button"], missing: Some("submit"), invalid: None },
    ReflectSpec { tag: "button", idl: "value", attr: "value", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "canvas", idl: "height", attr: "height", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("150"), invalid: None },
    ReflectSpec { tag: "canvas", idl: "width", attr: "width", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("300"), invalid: None },
    ReflectSpec { tag: "caption", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "col", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "col", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "col", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "col", idl: "span", attr: "span", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "col", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "col", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "colgroup", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "colgroup", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "colgroup", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "colgroup", idl: "span", attr: "span", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "colgroup", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "colgroup", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "data", idl: "value", attr: "value", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "del", idl: "cite", attr: "cite", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "del", idl: "dateTime", attr: "datetime", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "details", idl: "open", attr: "open", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "dialog", idl: "open", attr: "open", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "div", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "dl", idl: "compact", attr: "compact", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "embed", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "embed", idl: "height", attr: "height", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "embed", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "embed", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "embed", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "embed", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "fieldset", idl: "disabled", attr: "disabled", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "fieldset", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "form", idl: "acceptCharset", attr: "accept-charset", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "form", idl: "action", attr: "action", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "form", idl: "autocomplete", attr: "autocomplete", kind: Reflect::Enum, keywords: &["on", "off"], missing: Some("on"), invalid: None },
    ReflectSpec { tag: "form", idl: "encoding", attr: "enctype", kind: Reflect::Enum, keywords: &["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], missing: Some("application/x-www-form-urlencoded"), invalid: None },
    ReflectSpec { tag: "form", idl: "enctype", attr: "enctype", kind: Reflect::Enum, keywords: &["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], missing: Some("application/x-www-form-urlencoded"), invalid: None },
    ReflectSpec { tag: "form", idl: "method", attr: "method", kind: Reflect::Enum, keywords: &["get", "post", "dialog"], missing: Some("get"), invalid: None },
    ReflectSpec { tag: "form", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "form", idl: "noValidate", attr: "novalidate", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "form", idl: "target", attr: "target", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "h1", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "h2", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "h3", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "h4", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "h5", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "h6", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "hr", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "hr", idl: "color", attr: "color", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "hr", idl: "noShade", attr: "noshade", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "hr", idl: "size", attr: "size", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "hr", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "html", idl: "version", attr: "version", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "allowFullscreen", attr: "allowfullscreen", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "frameBorder", attr: "frameborder", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "height", attr: "height", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "longDesc", attr: "longdesc", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "marginHeight", attr: "marginheight", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "marginWidth", attr: "marginwidth", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "referrerPolicy", attr: "referrerpolicy", kind: Reflect::Enum, keywords: &["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "sandbox", attr: "sandbox", kind: Reflect::TokenList, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "scrolling", attr: "scrolling", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "srcdoc", attr: "srcdoc", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "iframe", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "alt", attr: "alt", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "border", attr: "border", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "crossOrigin", attr: "crossorigin", kind: Reflect::Enum, keywords: &["anonymous", "use-credentials"], missing: None, invalid: Some("anonymous") },
    ReflectSpec { tag: "img", idl: "decoding", attr: "decoding", kind: Reflect::Enum, keywords: &["async", "sync", "auto"], missing: Some("auto"), invalid: Some("auto") },
    ReflectSpec { tag: "img", idl: "height", attr: "height", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "hspace", attr: "hspace", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "isMap", attr: "ismap", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "longDesc", attr: "longdesc", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "lowsrc", attr: "lowsrc", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "referrerPolicy", attr: "referrerpolicy", kind: Reflect::Enum, keywords: &["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "srcset", attr: "srcset", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "useMap", attr: "usemap", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "vspace", attr: "vspace", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "img", idl: "width", attr: "width", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "accept", attr: "accept", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "alt", attr: "alt", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "autocomplete", attr: "autocomplete", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "defaultChecked", attr: "checked", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "defaultValue", attr: "value", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "dirName", attr: "dirname", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "disabled", attr: "disabled", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "formAction", attr: "formaction", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "formEnctype", attr: "formenctype", kind: Reflect::Enum, keywords: &["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"], missing: None, invalid: Some("application/x-www-form-urlencoded") },
    ReflectSpec { tag: "input", idl: "formMethod", attr: "formmethod", kind: Reflect::Enum, keywords: &["get", "post"], missing: None, invalid: Some("get") },
    ReflectSpec { tag: "input", idl: "formNoValidate", attr: "formnovalidate", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "formTarget", attr: "formtarget", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "height", attr: "height", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "max", attr: "max", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "maxLength", attr: "maxlength", kind: Reflect::Long, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "min", attr: "min", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "minLength", attr: "minlength", kind: Reflect::Long, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "multiple", attr: "multiple", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "pattern", attr: "pattern", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "placeholder", attr: "placeholder", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "readOnly", attr: "readonly", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "required", attr: "required", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "size", attr: "size", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("20"), invalid: None },
    ReflectSpec { tag: "input", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "step", attr: "step", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "type", attr: "type", kind: Reflect::Enum, keywords: &["hidden", "text", "search", "tel", "url", "email", "password", "date", "time", "datetime-local", "number", "range", "color", "checkbox", "radio", "file", "submit", "image", "reset", "button"], missing: Some("text"), invalid: None },
    ReflectSpec { tag: "input", idl: "useMap", attr: "usemap", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "input", idl: "width", attr: "width", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "ins", idl: "cite", attr: "cite", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "ins", idl: "dateTime", attr: "datetime", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "label", idl: "htmlFor", attr: "for", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "legend", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "li", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "li", idl: "value", attr: "value", kind: Reflect::Long, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "as", attr: "as", kind: Reflect::Enum, keywords: &["fetch", "audio", "document", "embed", "font", "image", "manifest", "object", "report", "script", "sharedworker", "style", "track", "video", "worker", "xslt"], missing: Some(""), invalid: Some("") },
    ReflectSpec { tag: "link", idl: "charset", attr: "charset", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "crossOrigin", attr: "crossorigin", kind: Reflect::Enum, keywords: &["anonymous", "use-credentials"], missing: None, invalid: Some("anonymous") },
    ReflectSpec { tag: "link", idl: "href", attr: "href", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "hreflang", attr: "hreflang", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "integrity", attr: "integrity", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "media", attr: "media", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "nonce", attr: "nonce", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "referrerPolicy", attr: "referrerpolicy", kind: Reflect::Enum, keywords: &["", "no-referrer", "no-referrer-when-downgrade", "same-origin", "origin", "strict-origin", "origin-when-cross-origin", "strict-origin-when-cross-origin", "unsafe-url"], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "rel", attr: "rel", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "relList", attr: "rel", kind: Reflect::TokenList, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "rev", attr: "rev", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "sizes", attr: "sizes", kind: Reflect::TokenList, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "target", attr: "target", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "link", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "map", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "menu", idl: "compact", attr: "compact", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meta", idl: "content", attr: "content", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meta", idl: "httpEquiv", attr: "http-equiv", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meta", idl: "media", attr: "media", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meta", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meta", idl: "scheme", attr: "scheme", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meter", idl: "high", attr: "high", kind: Reflect::Double, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meter", idl: "low", attr: "low", kind: Reflect::Double, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meter", idl: "max", attr: "max", kind: Reflect::Double, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meter", idl: "min", attr: "min", kind: Reflect::Double, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meter", idl: "optimum", attr: "optimum", kind: Reflect::Double, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "meter", idl: "value", attr: "value", kind: Reflect::Double, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "archive", attr: "archive", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "border", attr: "border", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "code", attr: "code", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "codeBase", attr: "codebase", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "codeType", attr: "codetype", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "data", attr: "data", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "declare", attr: "declare", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "height", attr: "height", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "hspace", attr: "hspace", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "standby", attr: "standby", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "useMap", attr: "usemap", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "vspace", attr: "vspace", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "object", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "ol", idl: "compact", attr: "compact", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "ol", idl: "reversed", attr: "reversed", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "ol", idl: "start", attr: "start", kind: Reflect::Long, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "ol", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "optgroup", idl: "disabled", attr: "disabled", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "optgroup", idl: "label", attr: "label", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "option", idl: "defaultSelected", attr: "selected", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "option", idl: "disabled", attr: "disabled", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "option", idl: "label", attr: "label", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "option", idl: "value", attr: "value", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "output", idl: "htmlFor", attr: "for", kind: Reflect::TokenList, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "output", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "p", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "param", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "param", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "param", idl: "value", attr: "value", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "param", idl: "valueType", attr: "valuetype", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "pre", idl: "width", attr: "width", kind: Reflect::Long, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "progress", idl: "max", attr: "max", kind: Reflect::Double, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "q", idl: "cite", attr: "cite", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "charset", attr: "charset", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "crossOrigin", attr: "crossorigin", kind: Reflect::Enum, keywords: &["anonymous", "use-credentials"], missing: None, invalid: Some("anonymous") },
    ReflectSpec { tag: "script", idl: "defer", attr: "defer", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "event", attr: "event", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "htmlFor", attr: "for", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "integrity", attr: "integrity", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "noModule", attr: "nomodule", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "script", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "select", idl: "autocomplete", attr: "autocomplete", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "select", idl: "disabled", attr: "disabled", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "select", idl: "multiple", attr: "multiple", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "select", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "select", idl: "required", attr: "required", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "select", idl: "size", attr: "size", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("0"), invalid: None },
    ReflectSpec { tag: "slot", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "source", idl: "media", attr: "media", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "source", idl: "sizes", attr: "sizes", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "source", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "source", idl: "srcset", attr: "srcset", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "source", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "style", idl: "media", attr: "media", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "style", idl: "nonce", attr: "nonce", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "style", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "bgColor", attr: "bgcolor", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "border", attr: "border", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "cellPadding", attr: "cellpadding", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "cellSpacing", attr: "cellspacing", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "frame", attr: "frame", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "rules", attr: "rules", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "summary", attr: "summary", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "table", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tbody", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tbody", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tbody", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tbody", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "abbr", attr: "abbr", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "axis", attr: "axis", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "bgColor", attr: "bgcolor", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "colSpan", attr: "colspan", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "td", idl: "headers", attr: "headers", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "height", attr: "height", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "noWrap", attr: "nowrap", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "rowSpan", attr: "rowspan", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "td", idl: "scope", attr: "scope", kind: Reflect::Enum, keywords: &["row", "col", "rowgroup", "colgroup"], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "td", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "autocomplete", attr: "autocomplete", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "cols", attr: "cols", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("20"), invalid: None },
    ReflectSpec { tag: "textarea", idl: "dirName", attr: "dirname", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "disabled", attr: "disabled", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "maxLength", attr: "maxlength", kind: Reflect::Long, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "minLength", attr: "minlength", kind: Reflect::Long, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "name", attr: "name", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "placeholder", attr: "placeholder", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "readOnly", attr: "readonly", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "required", attr: "required", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "textarea", idl: "rows", attr: "rows", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("2"), invalid: None },
    ReflectSpec { tag: "textarea", idl: "wrap", attr: "wrap", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tfoot", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tfoot", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tfoot", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tfoot", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "abbr", attr: "abbr", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "axis", attr: "axis", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "bgColor", attr: "bgcolor", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "colSpan", attr: "colspan", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "th", idl: "headers", attr: "headers", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "height", attr: "height", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "noWrap", attr: "nowrap", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "rowSpan", attr: "rowspan", kind: Reflect::UnsignedLong, keywords: &[], missing: Some("1"), invalid: None },
    ReflectSpec { tag: "th", idl: "scope", attr: "scope", kind: Reflect::Enum, keywords: &["row", "col", "rowgroup", "colgroup"], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "th", idl: "width", attr: "width", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "thead", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "thead", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "thead", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "thead", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "time", idl: "dateTime", attr: "datetime", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tr", idl: "align", attr: "align", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tr", idl: "bgColor", attr: "bgcolor", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tr", idl: "ch", attr: "char", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tr", idl: "chOff", attr: "charoff", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "tr", idl: "vAlign", attr: "valign", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "track", idl: "default", attr: "default", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "track", idl: "kind", attr: "kind", kind: Reflect::Enum, keywords: &["subtitles", "captions", "descriptions", "chapters", "metadata"], missing: Some("subtitles"), invalid: Some("metadata") },
    ReflectSpec { tag: "track", idl: "label", attr: "label", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "track", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "track", idl: "srclang", attr: "srclang", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "ul", idl: "compact", attr: "compact", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "ul", idl: "type", attr: "type", kind: Reflect::String, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "undefinedelement", idl: "enterKeyHint", attr: "enterkeyhint", kind: Reflect::Enum, keywords: &["enter", "done", "go", "next", "previous", "search", "send"], missing: None, invalid: None },
    ReflectSpec { tag: "undefinedelement", idl: "inputMode", attr: "inputmode", kind: Reflect::Enum, keywords: &["none", "text", "tel", "url", "email", "numeric", "decimal", "search"], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "autoplay", attr: "autoplay", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "controls", attr: "controls", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "controlsList", attr: "controlslist", kind: Reflect::TokenList, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "crossOrigin", attr: "crossorigin", kind: Reflect::Enum, keywords: &["anonymous", "use-credentials"], missing: None, invalid: Some("anonymous") },
    ReflectSpec { tag: "video", idl: "defaultMuted", attr: "muted", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "height", attr: "height", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "loading", attr: "loading", kind: Reflect::Enum, keywords: &["lazy", "eager"], missing: Some("eager"), invalid: Some("eager") },
    ReflectSpec { tag: "video", idl: "loop", attr: "loop", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "playsInline", attr: "playsinline", kind: Reflect::Bool, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "poster", attr: "poster", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "preload", attr: "preload", kind: Reflect::Enum, keywords: &["none", "metadata", "auto"], missing: Some("['none', 'metadata', 'auto']"), invalid: None },
    ReflectSpec { tag: "video", idl: "src", attr: "src", kind: Reflect::Url, keywords: &[], missing: None, invalid: None },
    ReflectSpec { tag: "video", idl: "width", attr: "width", kind: Reflect::UnsignedLong, keywords: &[], missing: None, invalid: None },
];
